# Generated by Django 4.1.4 on 2022-12-18 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Printer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("api_key", models.CharField(blank=True, max_length=60, unique=True)),
                (
                    "check_type",
                    models.CharField(
                        choices=[("kitchen", "kitchen"), ("client", "client")],
                        max_length=60,
                    ),
                ),
                ("point_id", models.IntegerField()),
            ],
            options={
                "unique_together": {("check_type", "point_id")},
            },
        ),
        migrations.CreateModel(
            name="Check",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("kitchen", "kitchen"), ("client", "client")],
                        max_length=60,
                    ),
                ),
                ("order", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "new"),
                            ("rendered", "rendered"),
                            ("printed", "printed"),
                        ],
                        default="new",
                        max_length=60,
                    ),
                ),
                ("pdf_file", models.FileField(blank=True, null=True, upload_to="pdf/")),
                (
                    "printer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="restaurant_api.printer",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
